text = str(input("matnni kiriting: "))
a0 = text.find("0")
a1 = text.find("1")
a2 = text.find("2")
a3 = text.find("3")
a4 = text.find("4")
a5 = text.find("5")
a6 = text.find("6")
a7 = text.find("7")
a8 = text.find("8")
a9 = text.find("9")
if a0 != -1 or a1 != -1 or  a2 != -1 or a3 != -1 or a4 != -1 or a5 != -1 or  a6 != -1 or a7 != -1 or a8 != -1 or a9 != -1: print("bu matn tarkibida raqam mavjud")
else: print("bu matn tarkibida raqam mavjud emas")